name: Auto-Generate Docs

on:
  push:
    branches: [main]
    paths:
      - 'screens/**'
      - 'components/**'
      - 'server/**'
      - 'docgen.js'

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install axios
        run: npm install axios

      - name: Generate documentation
        run: node docgen.js
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Commit and push docs
        run: |
          git config --local user.name "docs-bot"
          git config --local user.email "actions@github.com"
          git add docs
          if git diff --cached --quiet; then
            echo "🟢 No changes to commit"
          else
            git commit -m "docs: auto-update markdown docs [skip ci]"
            git push origin HEAD:${{ github.ref }}
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
