name: Auto-Generate Documentation

on:
  workflow_dispatch:
  push:
    paths:
      - 'screens/**'
      - 'server/**'
      - 'App.js'

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install axios dotenv

      - name: Generate documentation
        run: node docgen.js
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          
      - name: Commit & push generated docs
        if: success()                         # only run if doc generation succeeded
        run: |
          git config --local user.name  "docs-bot"
          git config --local user.email "actions@github.com"

          # Check if anything in /docs changed
          if [[ -n "$(git status --porcelain docs)" ]]; then
            git add docs
            git commit -m "chore(docs): auto-update generated docs [skip ci]"
            git push origin HEAD:${{ github.ref }}
          else
            echo "No changes to commit"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
